Add osu! beatmap atlas to beatmap search tools
osucord/resources pull request #49
Opened 2024-10-02 03:40 UTC by Ameobea

The [osu! beatmap atlas](https://osu-atlas.ameo.dev) is a little tool I built that uses an embedding visualization to place similar beatmaps near each other.  It's useful to visualize your own top plays in the context of the broader osu universe as well as to find new maps to farm.

I came across your really nicely organized site and thought it might be a nice inclusion.  If not no worries at all of course.

Feel free to re-word the description or anything else as well.

Thanks for putting together and maintaining this great reosurce!

2024-10-02 15:40 UTC, ekgame requested changes
Hey, thanks for contributing! This looks like a great addition and I'm kicking myself that I forgot about it until now. I guess that's why we have the list.

I'd just like to simplify the description and I think it'll be great.

2024-10-02 15:40 UTC, ekgame commented on content.md
> +- [osu! Beatmap Atlas](https://osu-atlas.ameo.dev/) - An embedding-based tool that groups similar beatmaps together in space
```suggestion
- [osu! Beatmap Atlas](https://osu-atlas.ameo.dev/) - A map that groups similar beatmaps together in space
```
I don't think "embeddings" mean anything to the general userbase, so I suggest simplifying it to "a map".

2024-10-02 15:50 UTC, Ameobea commented
Good idea and agreed

2024-10-04 21:03 UTC, jamesbt365 approved these changes

2024-10-04 21:03 UTC, merged